version: '3'
services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    networks:
      - backend
    environment:
      - NODE_ENV=production

networks:
  backend:
    driver: bridge
