version: '3'
services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lyratech-web
    restart: always
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - frontend
    labels:
      - "dev.dozzle.group=lyratech"

networks:
  frontend:
    driver: bridge