"""Static catalog for the Diagnóstico GO feature: target services and default questions.

Question/option `value`s are stable English keys used for scoring and for
`normalized_answers_en`; only the labels are translated per locale.
"""

SERVICE_KEYS = ["process_automation", "fixed_price_project", "dedicated_team"]

SERVICE_CATALOG = {
    "process_automation": {
        "name": {
            "es": "Automatización de Procesos",
            "en": "Process Automation",
            "fr": "Automatisation des processus",
            "de": "Prozessautomatisierung",
        },
        "description": {
            "es": "Eliminamos tareas repetitivas con integraciones o IA, según lo que tu negocio necesita.",
            "en": "We eliminate repetitive tasks with integrations or AI, depending on what your business needs.",
            "fr": "Nous éliminons les tâches répétitives grâce à des intégrations ou à l'IA, selon vos besoins.",
            "de": "Wir eliminieren wiederkehrende Aufgaben durch Integrationen oder KI, je nach Bedarf deines Unternehmens.",
        },
    },
    "fixed_price_project": {
        "name": {
            "es": "Proyecto a Precio Fijo",
            "en": "Fixed-Price Project",
            "fr": "Projet à prix fixe",
            "de": "Festpreisprojekt",
        },
        "description": {
            "es": "Alcance cerrado, costo definido y entrega garantizada. Ideal para MVPs y fases claras.",
            "en": "Closed scope, defined cost, and guaranteed delivery. Ideal for MVPs and clear phases.",
            "fr": "Périmètre fermé, coût défini et livraison garantie. Idéal pour les MVP et les phases claires.",
            "de": "Fester Umfang, definierte Kosten und garantierte Lieferung. Ideal für MVPs und klare Phasen.",
        },
    },
    "dedicated_team": {
        "name": {
            "es": "Equipo Dedicado",
            "en": "Dedicated Team",
            "fr": "Équipe dédiée",
            "de": "Dediziertes Team",
        },
        "description": {
            "es": "Tu squad tecnológico ágil, completo y escalable. Capacidad operativa estable por horas.",
            "en": "Your agile, complete, and scalable tech squad. Stable operating capacity billed hourly.",
            "fr": "Votre squad technologique agile, complète et évolutive. Capacité opérationnelle stable à l'heure.",
            "de": "Dein agiles, vollständiges und skalierbares Tech-Squad. Stabile Kapazität auf Stundenbasis.",
        },
    },
}


def _opt(value: str, es: str, en: str, fr: str, de: str, **weights: int) -> dict:
    return {
        "value": value,
        "labels": {"es": es, "en": en, "fr": fr, "de": de},
        "score_weights": {key: weights.get(key, 0) for key in SERVICE_KEYS},
    }


DEFAULT_QUESTIONS_SEED = [
    {
        "key": "main_goal",
        "type": "single_choice",
        "sort_order": 1,
        "is_required": True,
        "config_json": {
            "labels": {
                "es": "¿Qué te gustaría resolver principalmente?",
                "en": "What would you mainly like to solve?",
                "fr": "Qu'aimeriez-vous résoudre principalement ?",
                "de": "Was möchtest du hauptsächlich lösen?",
            },
            "placeholder": {"es": "", "en": "", "fr": "", "de": ""},
            "help_text": {"es": "", "en": "", "fr": "", "de": ""},
            "options": [
                _opt("reduce_manual_work",
                     "Reducir trabajo manual y repetitivo",
                     "Reduce manual, repetitive work",
                     "Réduire le travail manuel répétitif",
                     "Manuelle, sich wiederholende Arbeit reduzieren",
                     process_automation=3),
                _opt("build_new_product",
                     "Construir un producto o MVP nuevo",
                     "Build a new product or MVP",
                     "Créer un nouveau produit ou MVP",
                     "Ein neues Produkt oder MVP entwickeln",
                     fixed_price_project=3),
                _opt("improve_existing_system",
                     "Mejorar o ampliar un sistema que ya tenemos",
                     "Improve or extend a system we already have",
                     "Améliorer ou étendre un système que nous avons déjà",
                     "Ein bestehendes System verbessern oder erweitern",
                     fixed_price_project=2, process_automation=1),
                _opt("scale_team_capacity",
                     "Aumentar la capacidad de mi equipo de desarrollo de software o TI",
                     "Increase the capacity of my software development or IT team",
                     "Augmenter la capacité de mon équipe de développement logiciel ou informatique",
                     "Die Kapazität meines Software-Entwicklungs- oder IT-Teams erhöhen",
                     dedicated_team=3),
                _opt("not_sure",
                     "Aún no lo tengo claro",
                     "I'm not sure yet",
                     "Je ne sais pas encore",
                     "Ich bin mir noch nicht sicher"),
            ],
        },
    },
    {
        "key": "project_stage",
        "type": "single_choice",
        "sort_order": 2,
        "is_required": True,
        "config_json": {
            "labels": {
                "es": "¿En qué etapa está tu proyecto?",
                "en": "What stage is your project at?",
                "fr": "À quel stade en est votre projet ?",
                "de": "In welcher Phase befindet sich dein Projekt?",
            },
            "placeholder": {"es": "", "en": "", "fr": "", "de": ""},
            "help_text": {"es": "", "en": "", "fr": "", "de": ""},
            "options": [
                _opt("just_identified_problem",
                     "Solo identificamos el problema, no sabemos la solución",
                     "We've only identified the problem, not the solution",
                     "Nous avons seulement identifié le problème, pas la solution",
                     "Wir haben nur das Problem erkannt, noch nicht die Lösung"),
                _opt("rough_idea_undocumented",
                     "Tenemos una idea general, sin documentar",
                     "We have a general idea, not documented",
                     "Nous avons une idée générale, non documentée",
                     "Wir haben eine grobe Idee, nicht dokumentiert",
                     dedicated_team=1),
                _opt("preliminary_scope",
                     "Ya tenemos alcance o requerimientos preliminares",
                     "We already have a preliminary scope or requirements",
                     "Nous avons déjà un périmètre ou des exigences préliminaires",
                     "Wir haben bereits einen vorläufigen Umfang oder Anforderungen",
                     fixed_price_project=2),
                _opt("existing_system_to_improve",
                     "Ya existe un sistema o proceso funcionando que queremos mejorar",
                     "A system or process already works and we want to improve it",
                     "Un système ou processus fonctionne déjà et nous voulons l'améliorer",
                     "Es gibt bereits ein funktionierendes System oder einen Prozess, den wir verbessern möchten",
                     process_automation=2),
                _opt("defined_need_more_hands",
                     "El trabajo ya está definido, nos falta gente para ejecutarlo",
                     "The work is already defined, we just need more hands to execute it",
                     "Le travail est déjà défini, il nous manque des ressources pour l'exécuter",
                     "Die Arbeit ist bereits definiert, uns fehlen nur die Kapazitäten zur Umsetzung",
                     dedicated_team=2),
            ],
        },
    },
    {
        "key": "expected_outcome",
        "type": "single_choice",
        "sort_order": 3,
        "is_required": True,
        "config_json": {
            "labels": {
                "es": "¿Qué resultado esperas obtener primero?",
                "en": "What result are you hoping to get first?",
                "fr": "Quel résultat espérez-vous obtenir en premier ?",
                "de": "Welches Ergebnis erhoffst du dir zuerst?",
            },
            "placeholder": {"es": "", "en": "", "fr": "", "de": ""},
            "help_text": {"es": "", "en": "", "fr": "", "de": ""},
            "options": [
                _opt("save_time_reduce_errors",
                     "Ahorrar tiempo y reducir errores",
                     "Save time and reduce errors",
                     "Gagner du temps et réduire les erreurs",
                     "Zeit sparen und Fehler reduzieren",
                     process_automation=2),
                _opt("launch_defined_deliverable",
                     "Lanzar un producto o proyecto con alcance definido (MVP o completo)",
                     "Launch a product or project with a defined scope (MVP or complete)",
                     "Lancer un produit ou projet avec un périmètre défini (MVP ou complet)",
                     "Ein Produkt oder Projekt mit definiertem Umfang starten (MVP oder vollständig)",
                     fixed_price_project=2),
                _opt("improve_existing_experience",
                     "Mejorar el rendimiento o la experiencia de algo que ya existe",
                     "Improve the performance or experience of something that already exists",
                     "Améliorer la performance ou l'expérience de quelque chose qui existe déjà",
                     "Die Leistung oder das Erlebnis von etwas Bestehendem verbessern",
                     fixed_price_project=1),
                _opt("move_faster_with_support",
                     "Avanzar más rápido con apoyo técnico continuo",
                     "Move faster with ongoing technical support",
                     "Avancer plus vite avec un soutien technique continu",
                     "Schneller vorankommen mit fortlaufender technischer Unterstützung",
                     dedicated_team=2),
                _opt("not_sure_outcome",
                     "Aún no tengo claro el resultado esperado",
                     "I'm not sure yet what result to expect",
                     "Je ne sais pas encore quel résultat attendre",
                     "Ich bin mir noch nicht sicher, welches Ergebnis ich erwarte"),
            ],
        },
    },
    {
        "key": "automation_shape",
        "type": "single_choice",
        "sort_order": 4,
        "is_required": False,
        "config_json": {
            "labels": {
                "es": "¿Cómo funciona lo que quieres automatizar?",
                "en": "How does what you want to automate work?",
                "fr": "Comment fonctionne ce que vous voulez automatiser ?",
                "de": "Wie funktioniert das, was du automatisieren möchtest?",
            },
            "placeholder": {"es": "", "en": "", "fr": "", "de": ""},
            "help_text": {"es": "", "en": "", "fr": "", "de": ""},
            "options": [
                _opt("fixed_rules",
                     "Sigue pasos y reglas siempre iguales",
                     "Follows fixed, repeatable steps and rules",
                     "Suit des étapes et règles toujours identiques",
                     "Folgt immer gleichen Schritten und Regeln",
                     process_automation=1),
                _opt("context_or_language",
                     "Requiere leer o interpretar texto, documentos o conversaciones",
                     "Requires reading or interpreting text, documents, or conversations",
                     "Nécessite de lire ou d'interpréter du texte, des documents ou des conversations",
                     "Erfordert das Lesen oder Interpretieren von Text, Dokumenten oder Gesprächen",
                     process_automation=1),
                _opt("mixed_rules_and_context",
                     "Es una mezcla de reglas fijas e interpretación",
                     "It's a mix of fixed rules and interpretation",
                     "C'est un mélange de règles fixes et d'interprétation",
                     "Es ist eine Mischung aus festen Regeln und Interpretation",
                     process_automation=1),
                _opt("not_sure_shape",
                     "Aún no lo sé",
                     "I'm not sure yet",
                     "Je ne sais pas encore",
                     "Ich bin mir noch nicht sicher"),
            ],
        },
    },
    {
        "key": "collaboration_model",
        "type": "single_choice",
        "sort_order": 5,
        "is_required": True,
        "config_json": {
            "labels": {
                "es": "¿Cómo te gustaría trabajar con nosotros?",
                "en": "How would you like to work with us?",
                "fr": "Comment aimeriez-vous travailler avec nous ?",
                "de": "Wie möchtest du mit uns zusammenarbeiten?",
            },
            "placeholder": {"es": "", "en": "", "fr": "", "de": ""},
            "help_text": {"es": "", "en": "", "fr": "", "de": ""},
            "options": [
                _opt("fixed_scope_cost_deadline",
                     "Con alcance, costo y fecha definidos",
                     "With a defined scope, cost, and deadline",
                     "Avec un périmètre, un coût et une date définis",
                     "Mit festgelegtem Umfang, Kosten und Termin",
                     fixed_price_project=3),
                _opt("phased_first_version",
                     "Por fases, empezando con una primera versión",
                     "In phases, starting with a first version",
                     "Par phases, en commençant par une première version",
                     "In Phasen, beginnend mit einer ersten Version",
                     fixed_price_project=2),
                _opt("continuous_flexible_capacity",
                     "Con capacidad de desarrollo continua y flexible",
                     "With continuous, flexible development capacity",
                     "Avec une capacité de développement continue et flexible",
                     "Mit kontinuierlicher, flexibler Entwicklungskapazität",
                     dedicated_team=3),
                _opt("prefer_recommendation",
                     "Prefiero que ustedes me recomienden",
                     "I'd rather you recommend the best fit",
                     "Je préfère que vous me recommandiez la meilleure option",
                     "Ich möchte, dass ihr mir das Passende empfehlt"),
            ],
        },
    },
    {
        "key": "tech_capacity",
        "type": "single_choice",
        "sort_order": 6,
        "is_required": True,
        "config_json": {
            "labels": {
                "es": "¿Con qué equipo de desarrollo de software o TI cuentan hoy?",
                "en": "What software development or IT team do you have today?",
                "fr": "De quelle équipe de développement logiciel ou informatique disposez-vous aujourd'hui ?",
                "de": "Über welches Software-Entwicklungs- oder IT-Team verfügt ihr heute?",
            },
            "placeholder": {"es": "", "en": "", "fr": "", "de": ""},
            "help_text": {"es": "", "en": "", "fr": "", "de": ""},
            "options": [
                _opt("no_internal_dev_team",
                     "No tenemos un equipo de desarrollo/TI interno",
                     "We don't have an in-house development/IT team",
                     "Nous n'avons pas d'équipe de développement/informatique en interne",
                     "Wir haben kein internes Entwicklungs-/IT-Team",
                     fixed_price_project=1, dedicated_team=1),
                _opt("small_team_overloaded",
                     "Tenemos equipo de desarrollo, pero está saturado",
                     "We have a development team, but it's overloaded",
                     "Nous avons une équipe de développement, mais elle est débordée",
                     "Wir haben ein Entwicklungsteam, aber es ist überlastet",
                     dedicated_team=2),
                _opt("team_needs_better_tools",
                     "Tenemos equipo de desarrollo y buscamos mejores herramientas o automatización",
                     "We have a development team and are looking for better tools or automation",
                     "Nous avons une équipe de développement et cherchons de meilleurs outils ou de l'automatisation",
                     "Wir haben ein Entwicklungsteam und suchen bessere Tools oder Automatisierung",
                     process_automation=2),
                _opt("works_with_freelancers_or_vendors",
                     "Trabajamos con freelancers u otros proveedores externos",
                     "We work with freelancers or other external vendors",
                     "Nous travaillons avec des freelances ou d'autres prestataires externes",
                     "Wir arbeiten mit Freelancern oder anderen externen Anbietern",
                     dedicated_team=1),
                _opt("enough_capacity",
                     "Tenemos la capacidad que necesitamos",
                     "We have the capacity we need",
                     "Nous avons la capacité dont nous avons besoin",
                     "Wir haben die Kapazität, die wir brauchen",
                     fixed_price_project=1),
                _opt("not_sure_capacity",
                     "No estoy seguro",
                     "I'm not sure",
                     "Je ne suis pas sûr",
                     "Ich bin mir nicht sicher"),
            ],
        },
    },
    {
        "key": "urgency",
        "type": "single_choice",
        "sort_order": 7,
        "is_required": True,
        "config_json": {
            "labels": {
                "es": "¿Cuándo te gustaría comenzar?",
                "en": "When would you like to get started?",
                "fr": "Quand aimeriez-vous commencer ?",
                "de": "Wann möchtest du starten?",
            },
            "placeholder": {"es": "", "en": "", "fr": "", "de": ""},
            "help_text": {"es": "", "en": "", "fr": "", "de": ""},
            "options": [
                _opt("within_1_month",
                     "Lo antes posible, en menos de un mes",
                     "As soon as possible, within a month",
                     "Le plus tôt possible, en moins d'un mois",
                     "So schnell wie möglich, innerhalb eines Monats"),
                _opt("within_1_to_3_months",
                     "En los próximos 1 a 3 meses",
                     "In the next 1 to 3 months",
                     "Dans les 1 à 3 prochains mois",
                     "In den nächsten 1 bis 3 Monaten"),
                _opt("within_3_to_6_months",
                     "En los próximos 3 a 6 meses",
                     "In the next 3 to 6 months",
                     "Dans les 3 à 6 prochains mois",
                     "In den nächsten 3 bis 6 Monaten"),
                _opt("just_exploring",
                     "Solo estoy explorando opciones",
                     "Just exploring options",
                     "Je ne fais qu'explorer les options",
                     "Ich sehe mich nur um"),
                _opt("no_date_yet",
                     "Aún no tenemos una fecha",
                     "We don't have a date yet",
                     "Nous n'avons pas encore de date",
                     "Wir haben noch kein Datum"),
            ],
        },
    },
    {
        "key": "open_challenge",
        "type": "open_text",
        "sort_order": 8,
        "is_required": True,
        "config_json": {
            "labels": {
                "es": "Cuéntanos un poco más sobre tu proyecto o idea",
                "en": "Tell us a bit more about your project or idea",
                "fr": "Parlez-nous un peu plus de votre projet ou de votre idée",
                "de": "Erzähl uns etwas mehr über dein Projekt oder deine Idee",
            },
            "placeholder": {
                "es": "Ej. Perdemos horas capturando datos manualmente cada semana...",
                "en": "E.g. We lose hours manually entering data every week...",
                "fr": "Ex. Nous perdons des heures à saisir des données chaque semaine...",
                "de": "Z.B. Wir verlieren jede Woche Stunden mit manueller Dateneingabe...",
            },
            "help_text": {
                "es": "¿Qué sucede actualmente, a quién afecta y qué te gustaría mejorar?",
                "en": "What's happening right now, who does it affect, and what would you like to improve?",
                "fr": "Que se passe-t-il actuellement, qui cela affecte-t-il et qu'aimeriez-vous améliorer ?",
                "de": "Was passiert gerade, wen betrifft es und was möchtest du verbessern?",
            },
            "options": [],
        },
    },
]
