"""Static catalog for the Diagnóstico GO feature: target services and default questions.

Question/option `value`s are stable English keys used for scoring and for
`normalized_answers_en`; only the labels are translated per locale.
"""

SERVICE_KEYS = ["process_automation", "fixed_price_project", "dedicated_team"]

SERVICE_CATALOG = {
    "process_automation": {
        "name": {
            "es": "Automatización de Procesos",
            "en": "Process Automation",
            "fr": "Automatisation des processus",
            "de": "Prozessautomatisierung",
        },
        "description": {
            "es": "Eliminamos tareas repetitivas con integraciones o IA, según lo que tu negocio necesita.",
            "en": "We eliminate repetitive tasks with integrations or AI, depending on what your business needs.",
            "fr": "Nous éliminons les tâches répétitives grâce à des intégrations ou à l'IA, selon vos besoins.",
            "de": "Wir eliminieren wiederkehrende Aufgaben durch Integrationen oder KI, je nach Bedarf deines Unternehmens.",
        },
    },
    "fixed_price_project": {
        "name": {
            "es": "Proyecto a Precio Fijo",
            "en": "Fixed-Price Project",
            "fr": "Projet à prix fixe",
            "de": "Festpreisprojekt",
        },
        "description": {
            "es": "Alcance cerrado, costo definido y entrega garantizada. Ideal para MVPs y fases claras.",
            "en": "Closed scope, defined cost, and guaranteed delivery. Ideal for MVPs and clear phases.",
            "fr": "Périmètre fermé, coût défini et livraison garantie. Idéal pour les MVP et les phases claires.",
            "de": "Fester Umfang, definierte Kosten und garantierte Lieferung. Ideal für MVPs und klare Phasen.",
        },
    },
    "dedicated_team": {
        "name": {
            "es": "Equipo Dedicado",
            "en": "Dedicated Team",
            "fr": "Équipe dédiée",
            "de": "Dediziertes Team",
        },
        "description": {
            "es": "Tu squad tecnológico ágil, completo y escalable. Capacidad operativa estable por horas.",
            "en": "Your agile, complete, and scalable tech squad. Stable operating capacity billed hourly.",
            "fr": "Votre squad technologique agile, complète et évolutive. Capacité opérationnelle stable à l'heure.",
            "de": "Dein agiles, vollständiges und skalierbares Tech-Squad. Stabile Kapazität auf Stundenbasis.",
        },
    },
}


def _opt(value: str, es: str, en: str, fr: str, de: str, **weights: int) -> dict:
    return {
        "value": value,
        "labels": {"es": es, "en": en, "fr": fr, "de": de},
        "score_weights": {key: weights.get(key, 0) for key in SERVICE_KEYS},
    }


DEFAULT_QUESTIONS_SEED = [
    {
        "key": "main_goal",
        "type": "single_choice",
        "sort_order": 1,
        "is_required": True,
        "config_json": {
            "labels": {
                "es": "¿Qué quieres lograr principalmente?",
                "en": "What do you mainly want to achieve?",
                "fr": "Que voulez-vous accomplir principalement ?",
                "de": "Was möchtest du hauptsächlich erreichen?",
            },
            "placeholder": {"es": "", "en": "", "fr": "", "de": ""},
            "help_text": {"es": "", "en": "", "fr": "", "de": ""},
            "options": [
                _opt("reduce_manual_work",
                     "Reducir trabajo manual y repetitivo",
                     "Reduce manual, repetitive work",
                     "Réduire le travail manuel répétitif",
                     "Manuelle, sich wiederholende Arbeit reduzieren",
                     process_automation=3),
                _opt("build_new_product",
                     "Construir un producto o MVP nuevo",
                     "Build a new product or MVP",
                     "Créer un nouveau produit ou MVP",
                     "Ein neues Produkt oder MVP entwickeln",
                     fixed_price_project=3),
                _opt("scale_team_capacity",
                     "Escalar la capacidad de mi equipo técnico",
                     "Scale my technical team's capacity",
                     "Renforcer la capacité de mon équipe technique",
                     "Die Kapazität meines technischen Teams erweitern",
                     dedicated_team=3),
                _opt("not_sure",
                     "Aún no lo tengo claro",
                     "I'm not sure yet",
                     "Je ne sais pas encore",
                     "Ich bin mir noch nicht sicher"),
            ],
        },
    },
    {
        "key": "current_situation",
        "type": "single_choice",
        "sort_order": 2,
        "is_required": True,
        "config_json": {
            "labels": {
                "es": "¿Cuál describe mejor tu situación actual?",
                "en": "Which best describes your current situation?",
                "fr": "Qu'est-ce qui décrit le mieux votre situation actuelle ?",
                "de": "Was beschreibt deine aktuelle Situation am besten?",
            },
            "placeholder": {"es": "", "en": "", "fr": "", "de": ""},
            "help_text": {"es": "", "en": "", "fr": "", "de": ""},
            "options": [
                _opt("have_process_not_working",
                     "Ya tenemos un proceso, pero no funciona bien",
                     "We already have a process, but it doesn't work well",
                     "Nous avons déjà un processus, mais il ne fonctionne pas bien",
                     "Wir haben bereits einen Prozess, aber er funktioniert nicht gut",
                     process_automation=2),
                _opt("starting_from_scratch",
                     "Estamos empezando desde cero",
                     "We're starting from scratch",
                     "Nous partons de zéro",
                     "Wir fangen bei null an",
                     fixed_price_project=2),
                _opt("have_backlog_need_hands",
                     "Tenemos backlog, pero nos faltan manos",
                     "We have a backlog, but need more hands",
                     "Nous avons un backlog, mais manquons de ressources",
                     "Wir haben einen Backlog, aber zu wenig Kapazität",
                     dedicated_team=2),
            ],
        },
    },
    {
        "key": "main_pain",
        "type": "single_choice",
        "sort_order": 3,
        "is_required": True,
        "config_json": {
            "labels": {
                "es": "¿Cuál es tu principal dolor hoy?",
                "en": "What's your main pain point today?",
                "fr": "Quelle est votre principale difficulté aujourd'hui ?",
                "de": "Was ist heute dein größtes Problem?",
            },
            "placeholder": {"es": "", "en": "", "fr": "", "de": ""},
            "help_text": {"es": "", "en": "", "fr": "", "de": ""},
            "options": [
                _opt("repetitive_manual_tasks",
                     "Tareas repetitivas que consumen tiempo",
                     "Repetitive tasks that eat up time",
                     "Des tâches répétitives qui prennent du temps",
                     "Wiederkehrende Aufgaben, die viel Zeit kosten",
                     process_automation=2),
                _opt("no_clear_scope_or_mvp",
                     "No tenemos un alcance claro ni un MVP",
                     "No clear scope or MVP",
                     "Pas de périmètre clair ni de MVP",
                     "Kein klarer Umfang oder MVP",
                     fixed_price_project=2),
                _opt("not_enough_dev_capacity",
                     "No tenemos suficiente capacidad de desarrollo",
                     "Not enough development capacity",
                     "Pas assez de capacité de développement",
                     "Nicht genug Entwicklungskapazität",
                     dedicated_team=2),
            ],
        },
    },
    {
        "key": "needs_context_or_rules",
        "type": "single_choice",
        "sort_order": 4,
        "is_required": True,
        "config_json": {
            "labels": {
                "es": "Lo que quieres automatizar o construir, ¿depende de reglas fijas o de entender contexto/lenguaje?",
                "en": "Does what you want to automate or build depend on fixed rules, or on understanding context/language?",
                "fr": "Ce que vous voulez automatiser dépend-il de règles fixes ou de la compréhension du contexte/langage ?",
                "de": "Hängt das, was du automatisieren möchtest, von festen Regeln oder vom Verständnis von Kontext/Sprache ab?",
            },
            "placeholder": {"es": "", "en": "", "fr": "", "de": ""},
            "help_text": {"es": "", "en": "", "fr": "", "de": ""},
            "options": [
                _opt("fixed_rules",
                     "De reglas fijas y repetibles",
                     "Fixed, repeatable rules",
                     "Des règles fixes et répétables",
                     "Feste, wiederholbare Regeln",
                     process_automation=1),
                _opt("context_or_language",
                     "De entender contexto o lenguaje natural",
                     "Understanding context or natural language",
                     "Comprendre le contexte ou le langage naturel",
                     "Kontext oder natürliche Sprache verstehen",
                     process_automation=1),
                _opt("not_applicable",
                     "No aplica a mi caso",
                     "Doesn't apply to my case",
                     "Ne s'applique pas à mon cas",
                     "Trifft auf meinen Fall nicht zu"),
            ],
        },
    },
    {
        "key": "what_first",
        "type": "single_choice",
        "sort_order": 5,
        "is_required": True,
        "config_json": {
            "labels": {
                "es": "¿Qué necesitas primero?",
                "en": "What do you need first?",
                "fr": "De quoi avez-vous besoin en premier ?",
                "de": "Was brauchst du zuerst?",
            },
            "placeholder": {"es": "", "en": "", "fr": "", "de": ""},
            "help_text": {"es": "", "en": "", "fr": "", "de": ""},
            "options": [
                _opt("connect_existing_systems",
                     "Conectar sistemas que ya usamos",
                     "Connect systems we already use",
                     "Connecter des systèmes que nous utilisons déjà",
                     "Bestehende Systeme verbinden",
                     process_automation=2),
                _opt("a_defined_deliverable",
                     "Un entregable con alcance definido",
                     "A deliverable with defined scope",
                     "Un livrable avec un périmètre défini",
                     "Ein Ergebnis mit definiertem Umfang",
                     fixed_price_project=2),
                _opt("ongoing_dev_squad",
                     "Un equipo de desarrollo continuo",
                     "An ongoing development squad",
                     "Une équipe de développement continue",
                     "Ein fortlaufendes Entwicklungsteam",
                     dedicated_team=2),
            ],
        },
    },
    {
        "key": "urgency",
        "type": "single_choice",
        "sort_order": 6,
        "is_required": True,
        "config_json": {
            "labels": {
                "es": "¿Qué tan urgente es este proyecto?",
                "en": "How urgent is this project?",
                "fr": "À quel point ce projet est-il urgent ?",
                "de": "Wie dringend ist dieses Projekt?",
            },
            "placeholder": {"es": "", "en": "", "fr": "", "de": ""},
            "help_text": {"es": "", "en": "", "fr": "", "de": ""},
            "options": [
                _opt("asap",
                     "Lo necesito lo antes posible",
                     "I need it as soon as possible",
                     "J'en ai besoin le plus tôt possible",
                     "Ich brauche es so schnell wie möglich"),
                _opt("this_quarter",
                     "En este trimestre",
                     "This quarter",
                     "Ce trimestre",
                     "In diesem Quartal"),
                _opt("exploring",
                     "Solo estoy explorando opciones",
                     "Just exploring options",
                     "Je ne fais qu'explorer les options",
                     "Ich sehe mich nur um"),
            ],
        },
    },
    {
        "key": "tech_team_status",
        "type": "single_choice",
        "sort_order": 7,
        "is_required": True,
        "config_json": {
            "labels": {
                "es": "¿Cómo está tu equipo técnico actual?",
                "en": "How is your current technical team?",
                "fr": "Comment se porte votre équipe technique actuelle ?",
                "de": "Wie ist der aktuelle Stand deines technischen Teams?",
            },
            "placeholder": {"es": "", "en": "", "fr": "", "de": ""},
            "help_text": {"es": "", "en": "", "fr": "", "de": ""},
            "options": [
                _opt("no_technical_team",
                     "No tenemos equipo técnico propio",
                     "We don't have an in-house technical team",
                     "Nous n'avons pas d'équipe technique en interne",
                     "Wir haben kein eigenes technisches Team",
                     fixed_price_project=1, dedicated_team=1),
                _opt("small_team_overloaded",
                     "Tenemos un equipo pequeño y saturado",
                     "We have a small, overloaded team",
                     "Nous avons une petite équipe débordée",
                     "Wir haben ein kleines, überlastetes Team",
                     dedicated_team=2),
                _opt("technical_team_needs_tools",
                     "Tenemos equipo técnico, pero necesita mejores herramientas",
                     "We have a technical team, but it needs better tools",
                     "Nous avons une équipe technique, mais elle a besoin de meilleurs outils",
                     "Wir haben ein technisches Team, das aber bessere Tools braucht",
                     process_automation=2),
            ],
        },
    },
    {
        "key": "project_definition",
        "type": "single_choice",
        "sort_order": 8,
        "is_required": True,
        "config_json": {
            "labels": {
                "es": "¿Qué tan definido tienes el proyecto?",
                "en": "How well-defined is the project?",
                "fr": "Dans quelle mesure le projet est-il défini ?",
                "de": "Wie gut ist das Projekt definiert?",
            },
            "placeholder": {"es": "", "en": "", "fr": "", "de": ""},
            "help_text": {"es": "", "en": "", "fr": "", "de": ""},
            "options": [
                _opt("fully_defined",
                     "Totalmente definido y documentado",
                     "Fully defined and documented",
                     "Entièrement défini et documenté",
                     "Vollständig definiert und dokumentiert",
                     fixed_price_project=2),
                _opt("rough_idea",
                     "Tengo una idea general, sin documentar",
                     "I have a general idea, not documented",
                     "J'ai une idée générale, non documentée",
                     "Ich habe eine grobe Idee, nicht dokumentiert",
                     dedicated_team=1),
                _opt("just_exploring",
                     "Apenas estoy explorando el problema",
                     "I'm just exploring the problem",
                     "Je ne fais qu'explorer le problème",
                     "Ich untersuche das Problem gerade erst"),
            ],
        },
    },
    {
        "key": "open_challenge",
        "type": "open_text",
        "sort_order": 9,
        "is_required": False,
        "config_json": {
            "labels": {
                "es": "Cuéntanos brevemente tu reto (opcional)",
                "en": "Briefly tell us about your challenge (optional)",
                "fr": "Décrivez brièvement votre défi (facultatif)",
                "de": "Beschreibe kurz deine Herausforderung (optional)",
            },
            "placeholder": {
                "es": "Ej. Perdemos horas capturando datos manualmente cada semana...",
                "en": "E.g. We lose hours manually entering data every week...",
                "fr": "Ex. Nous perdons des heures à saisir des données chaque semaine...",
                "de": "Z.B. Wir verlieren jede Woche Stunden mit manueller Dateneingabe...",
            },
            "help_text": {"es": "", "en": "", "fr": "", "de": ""},
            "options": [],
        },
    },
]
